### PR TITLE
A Little Housekeeping

### PR DESCRIPTION
**Pull request by nanake**
@BtbN 99-rpath.sh is 644. should it be 755?

### CODE REVIEW

**Comment by sudo-nautilus** [comment]
I've a question : how he merges ? squash or rebase ?

**Comment by nanake** [comment]
> I've a question : how he merges ? squash or rebase ?

Sorry, I don't follow. me or BtbN you're addressing?
merge of what? you mean this PR?

**Comment by sudo-nautilus** [comment]
> > I've a question : how he merges ? squash or rebase ?
> 
> Sorry, I don't follow. me or BtbN you're addressing?
> merge of what? you mean this PR?

Um, I'm addressing BtbN

**Comment by sudo-nautilus** [comment]
I mean merging PRs in which way, rebase merge or squash merge ?

**Comment by nanake** [comment]
Intermittent linux64-gpl failure:

`#66 ERROR: executor failed running [/bin/sh -c run_stage /stage.sh]: flightcontrol: exceeded retry timeout`

that's out of my control.

I've tested (only on windows) locally this CL can build into ffmpeg.

**Comment by BtbN** [comment]
I don't want any merge commits in the history, so won't ever do actual merges.
And if I can at all avoid it, I won't squash anything either, but instead ask for a proper granular history.

**Comment by sudo-nautilus** [comment]
> I don't want any merge commits in the history, so won't ever do actual merges.
> And if I can at all avoid it, I won't squash anything either, but instead ask for a proper granular history.

Oh I guess that means rebase merge, am I correct

**Pull request merged**
