### PR TITLE
Update mingw-w64

### PR DESCRIPTION
**Pull request by Kosm8**

### CODE REVIEW

**Comment by BtbN** [comment]
Who is running that mirror?
And what's up with the official one, if there's commits that are missing?

**Comment by Kosm8** [comment]
What missing commits are you talking about?

**Comment by BtbN** [comment]
The ones since end of march, which the official(?) mirror repo does not have.

**Comment by Kosm8** [comment]
This new mirror is up to date, but if the previous one was the official one then it's not updated anymore.

**Comment by BtbN** [comment]
Yes, that's exactly what and why I'm asking.
What is the current mirror situation? And who is running it? What happened to the official one? (And where are they actually mirroring from?)

**Pull request closed without merging**
