### PR TITLE
Fix variable name of fftw3 build script

### PR DESCRIPTION
**Pull request by bitraid**

### CODE REVIEW

**Comment by BtbN** [comment]
Given that every time I do a round of dependency updates _something_ breaks, a repo like that sounds like a massive hassle to keep in good condition :D

**Comment by bitraid** [comment]
Yeah, I thought that'd be the case. I guess I'll end up using the latest commits for only a few that interests me (like svt-av1).

**Comment by safetycar** [comment]
In case you want to check, I accidentally saw a similar thing at "scripts.d/50-vidstab.sh".

**Comment by bitraid** [comment]
Nice catch! Somehow I missed that one.

**Pull request merged**
