### PR TITLE
replace Windows 7 with Windows 10

### PR DESCRIPTION
**Pull request by Awire9966**
replace Windows 7 with Windows 10 in relation to #386

### CODE REVIEW

**Comment by BtbN** [comment]
The thing is, the builds _are_ targeting Windows 7.
It's just that some dependencies are doing something that doesn't work anymore.
I'm currently examining if it makes sense to change the toolchain target to Windows 10, or if that has other averse effects.

**Comment by Awire9966** [comment]
I see. I have fixed the Readme to reflect the info you have given me.

**Comment by Awire9966** [comment]
Updated information. The error seems to be a "Memory Access Violation" Error. Microsoft has an article about it, however the article relates to Windows Explorer. [Article](https://support.microsoft.com/en-us/topic/-0xc0000005-error-message-and-windows-explorer-stops-responding-on-a-computer-that-s-running-windows-7-sp1-or-windows-server-2008-r2-sp1-d92f8a4a-16fd-7c6e-3063-84a895b5958e)

**Comment by Awire9966** [comment]
> You need to install UCRT manually, msys2 mingw64 still uses msvcrt.

Does the ubuntu x86_64-w64-mingw32-gcc compiler use MSVCRT or UCRT? I cross-compiled using the same settings as i did on MSYS2, and my ubuntu build also works.

**Comment by Awire9966** [comment]
> I've been explicitly selecting ucrt since a while now, since it makes for a smaller and more secure build. Probably easily over a year, would have to check commit logs.
> 
> In any case, if that jeopardizes Win7 support, I'll just write Win 10 22H2 into the readme and call it a day.

A potential idea, you split the repo into a UCRT branch (main branch) and an MSVCRT branch. The MSVCRT branch would have the same scripts, just using MSVCRT rather than UCRT. I dont know how complicated that would be, but if its too complicated, changing the readme should work.

**Comment by BtbN** [comment]
No, nobody needed that in the last year. If someone really still wants to use Windows 7, which is just a terrible idea anyway, they can do the work themselves. I will put no effort into it.

**Comment by Awire9966** [comment]
> No, nobody needed that in the last year. If someone really still wants to use Windows 7, which is just a terrible idea anyway, they can do the work themselves. I will put no effort into it.

Well I added the requirement to the readme as well as some info.

**Pull request closed without merging**
