### PR TITLE
Add libssh

### LINKED ISSUE #158: Need help with enabling libssh
I made 50-libssh.sh similar to other libraries
https://github.com/megapro17/FFmpeg-Builds/blob/master/scripts.d/50-libssh.sh
It did compiled fine, but when building ffmpeg it says
`ERROR: libssh not found using pkg-config`
I've tried googling this mistake, but didn't found much info
https://github.com/megapro17/FFmpeg-Builds/runs/6779032432?check_suite_focus=true

libssh is adding support for reading and writing files from sftp server, which is very useful, because you can run encoding on remote machines without manual file transfers

### PR DESCRIPTION
**Pull request by nanake**
Closes #158

Signed-off-by: nanake <nanake@users.noreply.github.com>

### CODE REVIEW

**Comment by nanake** [comment]
Fast & Furious build passed. I just reuse the build cache from your repo, see the ci branch:
https://github.com/nanake/FFmpeg-Builds/commits/ci
https://github.com/nanake/FFmpeg-Builds/actions

**Comment by BtbN** [comment]
Both blowfish and dsa are not exactly strong ciphers. Are you sure those should be on?

**Comment by nanake** [comment]
Honestly, I just copied the options from their gitlab-CI. It can be removed then.

You want me to force push now or wait all tests to be finished?

**Comment by BtbN** [comment]
I'd wait for them to finish first.
btw., what's up with that global linker flag being added? That does not sound exactly safe. If there's colliding multiple definitions, that ought to be fixed or bad things might happen.

**Comment by nanake** [comment]
it's the same error on https://github.com/BtbN/FFmpeg-Builds/issues/158#issuecomment-1149261917 when build with ffmpeg.

```
multiple definition of `gettimeofday'
```

**Comment by BtbN** [comment]
That's actually a function defined in libssh: https://github.com/libssh/libssh-mirror/blob/master/src/misc.c#L161

Adding that linker flag to hide that error is not acceptable. It might pick the libssh function over the proper one, and break a whole bunch of other stuff.
Plus, it might in the future hide other collisions, leading to silently broken builds.

This needs to be raised upstream and fixed before it can be included. They probably need a configure-time check for the availability of gettimeofday, and then only include their wrapper if that's not available. And if so, probably still call it something else to not pointlessly risk collisions.

**Pull request merged**
