### PR TITLE
Clarify which Release tags are kept + fix autobuild retention time

### PR DESCRIPTION
**Pull request by dtugend**
See https://github.com/BtbN/FFmpeg-Builds/issues/129

### CODE REVIEW

**Comment by BtbN** [comment]
The change to the readme seems like it'd make it more confusing than clear?
The fix of the typo is fine by me, I don't remember if I intended it to be 12 or 24.

**Comment by dtugend** [comment]
> The change to the readme seems like it'd make it more confusing than clear?
For me it was more confusing before, because of the "latest" build being the "Last Build" mentioned in the readme, I was almost using the files of that to be honest.
But this is your repository, if you don't like it, then reject the pull request, please :)

> The fix of the typo is fine by me, I don't remember if I intended it to be 12 or 24.
It says 2 years in "README"-file, so it should be either 1 year there ot 24 here, I tried to solve it thise way.

**Comment by BtbN** [comment]
I've pushed a hopefully more clear explanation to the readme.

**Comment by dtugend** [comment]
Thank you 👍

**Pull request closed without merging**
