### PR TITLE
Ignore Readme Files In Workflow

### PR DESCRIPTION
**Pull request by sudo-nautilus**
This will ignore the running of the workflow file when someone pushes (commits) edits to a readme file or when someone pull requests readme ( markdown ) file.
If you merge this I'll try to pull request some readme edits contain badges.

### CODE REVIEW

**Comment by BtbN** [comment]
Please get rid of the merge commit.

**Comment by sudo-nautilus** [comment]
> Please get rid of the merge commit.

You mean what

**Comment by pzhlkj6612** [comment]
Hi @sudo-nautilus . I guess @BtbN meant that you should provide a linear history. In other words, the two commits should be on the same branch from the beginning.

**Comment by sudo-nautilus** [comment]
Ok thanks @pzhlkj6612

**Comment by sudo-nautilus** [comment]
Wew

**Comment by BtbN** [comment]
No need to close this, just force-push the rebased commits into your PR branch.

**Pull request closed without merging**
