### PR TITLE
Update libvpx to 1.3.1

### PR DESCRIPTION
**Pull request by daniel-stanciu**
Libvpx should be updated to be more explicit in the fact it includes the security patch.

### CODE REVIEW

**Comment by BtbN** [comment]
libvpx already is updated for the security issues.
And on top of that, I'm pretty confident ffmpeg is not affected by it either way, since there is no way to reconfigure the amount of threads at runtime.

**Comment by daniel-stanciu** [comment]
The main purpose of this PR was to avoid logs like `[libvpx @ 0000028df60bd7c0] v1.13.0` which might give a naive user the impression that the fix is not included and could cause unwarranted skepticism.

**Comment by BtbN** [comment]
Yeah, that is fair. Will merge once all checks are green.

**Comment by daniel-stanciu** [comment]
> Yeah, that is fair. Will merge once all checks are green.

Something seems to have failed.

**Comment by daniel-stanciu** [comment]
There seems to be a problem with the build machine
`System.IO.IOException: No space left on device :`

**Comment by BtbN** [comment]
This seems to be on Githubs end for all I can tell, there is no useful error output at all.

**Comment by daniel-stanciu** [comment]
I would have tried a rerun, but I probably don't have permissions.

**Comment by BtbN** [comment]
I'm getting other weird issues with the builds right now. The registry randomly not finding an image it just pushed. I'll just try again in a few hours.

**Comment by BtbN** [comment]
Can you rebase this against master? I did a bunch of fixes, and it might work now.

**Comment by daniel-stanciu** [comment]
Rebased

**Pull request merged**
