### PR TITLE
Add chromaprint

### PR DESCRIPTION
**Pull request by nyanmisaka**
chromaprint is used as a muxer to generate audio fingerprint.

### CODE REVIEW

**Comment by BtbN** [comment]
Does Chromaprint have a pkg-config file?
Adding flags via the global cflags is a relatively dirty workaround which can cause other issues and I try to avoid it as much as I can.
If it has one, I'll add a check for it to ffmpeg configure.

Also, does anything in layer 50 depend or below depend on this? Things should be as high up in the build order as possible. Adding it to 35 would potentially slow things down due to reduced parallelism.

**Comment by nyanmisaka** [comment]
> Does Chromaprint have a pkg-config file?

I think it is this one:
https://github.com/acoustid/chromaprint/blob/master/libchromaprint.pc.cmake
But I can't get it work unless I add these dirty hacks in ffmpeg extra flags.

> Also, does anything in layer 50 depend or below depend on this? Things should be as high up in the build order as possible. Adding it to 35 would potentially slow things down due to reduced parallelism.

Fixed. Moved it to 50.

**Comment by BtbN** [comment]
https://ffmpeg.org/pipermail/ffmpeg-devel/2022-November/303552.html

The NODLL flag you can just append to the .pc file like in a bunch of other scripts: https://github.com/BtbN/FFmpeg-Builds/blob/master/scripts.d/50-srt.sh#L21
Doesn't even need to be OS specific, it just does nothing elsewhere.

**Comment by nyanmisaka** [comment]
Thanks for your quick patch!
I'll re-push after it's been merged.

**Comment by BtbN** [comment]
Patch is merged upstream.
This will in turn only work on master.
If you add the same version limits OpenAL got (https://github.com/BtbN/FFmpeg-Builds/blob/master/scripts.d/50-openal.sh#L7) and add the needed flags to the .pc file instead of via global functions, this should be good to go.

**Comment by BtbN** [comment]
Merged manually.
No need to disable it on lgpl builds. Just remove the check from fftw3.
Also no need to use sed, can just echo it on as well.

**Pull request closed without merging**
