### PR TITLE
Roll release/4.4

### PR DESCRIPTION
**Pull request by nanake**
Updated! Unbitrotted! 

Sorry, i don't know how to done this on previous PR #60, hence re-PRing

### CODE REVIEW

**Comment by BtbN** [comment]
4.4 should actually be nearing release soon. Hopefully within the next few days.
There's still a few open issues in the release branch that are waiting for fixes.

**Comment by sudo-nautilus** [comment]
Everybody gangsta until FFmpeg 4.4 gets released

**Comment by BtbN** [comment]
There's going to be a few more disruptions, I'd recommend waiting until 4.4 is actually out to fix them :D

**Comment by nanake** [comment]
> There's going to be a few more disruptions, I'd recommend waiting until 4.4 is actually out to fix them :D

Roger Wilco! 

Hope it won't delay regarding CFHD.

**Comment by sudo-nautilus** [comment]
Hi there. I dunno it is better to ask it here, anyway I'm saying it.
Are you guys on Telegram or Discord ?
Im [@sudo_nautilus](https://t.me/sudo_nautilus) in Telegram and
Nautilus#0296 in Discord

**Comment by BtbN** [comment]
Neither, no.
I'm on Freenode in the respective FFmpeg channels though.

**Comment by sudo-nautilus** [comment]
> Neither, no.
> I'm on Freenode in the respective FFmpeg channels though.

oof

**Comment by nanake** [comment]
> Are you guys on Telegram or Discord ?

nah, im not on any of that.

**Comment by sudo-nautilus** [comment]
> > Are you guys on Telegram or Discord ?
> 
> nah, im not on any of that.

man

**Comment by sudo-nautilus** [comment]
> Neither, no.
> I'm on Freenode in the respective FFmpeg channels though.

kk lemme come to the irc

**Comment by nanake** [comment]
Im trying rebuild to see if `glslang` can build unto ffmpeg 4.4. Ill publish the rebase soon.

**Comment by nanake** [comment]
> Im trying rebuild to see if `glslang` can build unto ffmpeg 4.4. Ill publish the rebase soon.

successful build unto 4.4 :)

**Comment by sudo-nautilus** [comment]
I'll be doing that to my repo

**Pull request merged**
