### PR TITLE
libsvtav1: disable build the decoder

### PR DESCRIPTION
**Pull request by nanake**
Only the encoder is supported by FFmpeg,
so building of the decoder is disabled.

Signed-off-by: nanake <nanake@users.noreply.github.com>

### CODE REVIEW

**Comment by sudo-nautilus** [comment]
Hmm

**Comment by BtbN** [comment]
I kind of want to leave this enabled, on the off chance that at some future point, support for it is added to FFmpeg.
Or does it cause any issues, or is unreasonably large?

**Comment by nanake** [comment]
> Or does it cause any issues, or is unreasonably large?

Just spotted this bits on build. It slow building enough my eyes can notice this. 

> I kind of want to leave this enabled ...
 WFM, if you rule the objection. :D

**Comment by BtbN** [comment]
Yeah, let's just leave it in then. If at some point in the future, support for this decoder gets added, it'll just be picked up automatically.
I'm fine with an extra few 10 seconds build time.

**Pull request closed without merging**
