### PR TITLE
Add Readme Badges

### PR DESCRIPTION
**Pull request by sudo-nautilus**
Add some badges which are center aligned and looking fine (for me)

### CODE REVIEW

**Comment by sudo-nautilus** [comment]
No checks are running lol the code worked

**Comment by BtbN** [comment]
I'm not entirely sure if I'm a fan of this.
What value do those badges add that warrant the extra load time and pulling an otherwise unrelated third party service in?

**Comment by sudo-nautilus** [comment]
<div align=center>

windows autobuild architecture linux autobuild architecture GitHub all releases GitHub release (latest by date) GitHub issues closed issues

</div>

**Comment by sudo-nautilus** [comment]
It will look like this

**Comment by sudo-nautilus** [comment]
No extra load times,
Badges load after loading the page. The thing (service) is ope source actually. https://github.com/badges/shields ← this is it

**Comment by BtbN** [comment]
Yeah, I saw that. But I'd have expected that for example clicking the windows/linux ones links to the respective release, and not to the image itself.
And I'm really not a fan of exposing every visitor to a third-party service like that.
It also breaks a principle that I so far followed with this repo, in that forking it will immediately give you working builds for yourself. Those badges have the repos name hardcoded in.

So unless there is some really good benefit when adding those, I think I'd rather keep the readme simple and mostly plain text readable.

**Comment by sudo-nautilus** [comment]
Wait a sec,
I can do that,
I mean I can add what you just asked. Also make a tutorial on the topic 'how to reply faster'

**Comment by sudo-nautilus** [comment]
The badges are now functional,
By clicking the Architecture/Platform Badges 'Latest' page in wiki will open up,
By clicking download badge GitHub Releases (all) will open,
 By clicking the release badge, it will direct to today's release/latest release,
By clicking the issue badges, they will direct users to opened/closed issues just as they says it is opened or not.

**Comment by sudo-nautilus** [comment]
<div align=center>

[windows autobuild architecture](https://github.com/BtbN/FFmpeg-Builds/wiki/Latest) [linux autobuild architecture](https://github.com/BtbN/FFmpeg-Builds/wiki/Latest) [GitHub all releases](https://github.com/BtbN/FFmpeg-Builds/releases) [GitHub release (latest by date)](https://github.com/BtbN/FFmpeg-Builds/releases/latest) [GitHub issues](https://github.com/BtbN/FFmpeg-Builds/issues?q=is%3Aopen+is%3Aissue) [closed issues](https://github.com/BtbN/FFmpeg-Builds/issues?q=is%3Aissue+is%3Aclosed)

</div>

**Comment by sudo-nautilus** [comment]
@BtbN here's the updated preview

**Pull request closed without merging**
