### PR TITLE
Ability to build binaries on (not for) macOS (2nd attempt)

### PR DESCRIPTION
**Pull request by ffxsam**
Taking a different approach this time. The updated shebang (to `#!/usr/bin/env bash`) will ensure better portability, to start. There will also be some conditionals to use different commands/options, where necessary.

### CODE REVIEW

**Comment by BtbN** [comment]
I'll close this now, since I don't think it's a good idea to add or worth the effort.
For one, it has already confused people a couple times. And the total lack of support for building for OSX also makes it kinda pointless.

**Comment by thewh1teagle** [comment]
I'm really looking for macOS support as well. I can help by testing it on my Mac. Would you consider adding it?

**Comment by BtbN** [comment]
I think you are again misunderstanding.
This PR is/was NOT about building _for_ MacOS, but only _on_ it, still for Windows and Linux.
Apple does not support and actively prevents you from cross-compiling for its platform, so supporting it is impossible with the system the builds use.
I also have no MacOS capable PC, and no interest in getting one, so I couldn't test anything.

**Comment by ffxsam** [comment]
To be fair, macOS is technically *nix, and I was able to get this set of scripts to build ffmpeg on macOS. It just wasn't easy, and required a lot of conditionals. I think it would wind up being a maintenance headache. In the end, I just went with John van Sickle's static builds.

**Pull request closed without merging**
