### PR TITLE
Fix a mistake

### PR DESCRIPTION
**Pull request by skycommand**
Hello. 😊 And thank you for the great work on FFmpeg builds.

In this PR, I made the following changes to README.md. I hope you like them:

- Change the repo's description from "Static Windows Builds" to "Static and shared Windows builds." After all, you publish shared builds too. Oh, and thank you. I favor shared builds.
- Consistently capitalized the product name as "FFmpeg"
- A little grammatical improvement. The definite article was notably missing.

### CODE REVIEW

**Comment by BtbN** [comment]
This is not correct.
Static refers to all of the dependencies being linked statically, even on the builds which include the libav* libraries.
Also, this does build only ever the latest release branch, not all of them.

I'd strongly discourage using the shared version of the builds unless you need the libraries for some application that loads them.
If you just want to use the binaries, download the fully static version, to avoid any kind of DLL-Hell that might ensue when something else installed libav* DLLs into the PATH. Which happens more often than you think.

**Comment by BtbN** [comment]
Feel free to re-open this to fix just the grammar and capitalization!

**Comment by skycommand** [comment]
Hi again.
> I'd strongly discourage using the shared version of the builds unless you need the libraries for some application that loads them. If you just want to use the binaries, download the fully static version, to avoid any kind of DLL-Hell that might ensue when something else installed libav* DLLs into the PATH. Which happens more often than you think.

Two points here:
- The "DLL Hell" phenomenon to which you are referring belonged to the Windows 2000 era. It certainly doesn't happen on Windows Vista x64 and later. (Your releases are all for the `win64` target.) For details, see ["Dynamic-Link Library Search Order" § Standard Search Order for Desktop Applications](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-desktop-applications)
- Notice how you yourself referred to them as "shared" builds? That's how the language works.

I'll be using the shared builds for the foreseeable future and I'll remain grateful for you releasing them. 👍

> Also, this does build only ever the latest release branch, not all of them.

Sure, I can fix that. Here.

**Comment by BtbN** [comment]
I've literally had it happen to me on Windows 10, that something planted ffmpeg DLLs into System32, leading to very weird issues which took me pretty much a full day to figure out.
So it very much does still happen, not even only on Windows. Linux(and really any OS) also regularly has those issues where system libs clash with something you got in your home dir.
Just using the fully static binaries avoids the issue altogether.

**Comment by skycommand** [comment]
If that's true, you might win a bug bounty from Microsoft for disclosing a security vulnerability. All you need to do is to provide a reproducible list of instructions. I myself am very interested in seeing such proof.

But even if proven true, it means I must find a way to compile shared builds that don't suffer from this issue. It's shared builds for me, all the way. Not just because they are smaller and have higher performance, but because I'm a developer too.

**Comment by BtbN** [comment]
Proof for what?
Microsoft is not shipping ffmpeg DLLs as part of Windows. Some random third party installer dumped those there, and didn't bother cleaning them up.

A build using DLLs also has no performance advantage over one that has them built in. It's the same code, and the same size that needs loaded into RAM. If at all, the lack of indirection via the dynamic loader would yield a very slight performance advantage, but only on first call to a function.

**Comment by skycommand** [comment]
> Proof for what?
> Microsoft is not shipping ffmpeg DLLs as part of Windows. Some random third party installer dumped those there, and didn't bother cleaning them up.
First, I'm not saying you owe anyone anything. You are providing your releases voluntarily. Third parties have to clean up their own mess. And if you're not interested in what I said, we go about our lives. I continue to use shared builds and if something bad happened, it's on me, not you. Right?

Second, Microsoft is saying that Windows works in such-and-such ways. But, if you can prove that it doesn't (which counts as a bug,) you may be entitled to a prize. To do so, you have to make a set of instructions, (**if you are interested**) that if someone follows them on a clean installation of Windows, triggers the buggy behavior. Something like this: "(1) Copy `xyz.dll` and `xyz.exe` to `C:\xyz`. (2) Run `xyz.exe`. (3) Copy `%Windir%\System32\advapi32res.dll` into `%Windir%\System32\xyz.dll`.  (4) Run `xyz.exe` and see how it couldn't load `xyz.dll`."

> A build using DLLs also has no performance advantage over one that has them built in. It's the same code, and the same size that needs loaded into RAM.

On a one-off basis, no. But my apps or scripts can keep the DLLs in memory and use them in tandem with multiple jobs. Calling multiple `ffmpeg.exe`, on the other hand, loads it once for each job in separe memory spaces.

**Comment by BtbN** [comment]
I'd fully expect any repeated calls to a static ffmpeg.exe to be in the OS cache relatively soon as well, the the advantage there should be minimal.

And I still fail to see any bug in the behaviour of Windows there. It was following the usual and well defined search order. Just that a crappy installer had unloaded something in a higher priority location on the path, which thus ended up preferred, breaking the ffmpeg binary which ended up loading those DLLs.
Granted, this only happens if the binary for some reason get orphaned from its accompanying DLLs, but why take that risk in the first place?

**Comment by skycommand** [comment]
> Granted, this only happens if the binary for some reason get orphaned from its accompanying DLLs
Well, there you have it. No need to fear "DLL Hell"; in the decades that I used my computers, my `d3dcompiler_47.dll` was more than content to stay in the "Microsoft VS Code" folder and my `bink2w64.dll` has never demonstrated any tendency to sleepwalk out of its respective video game folder. I don't see why FFmpeg's DLLs must be any different.

Of course, none of these have any bearing on the PR at hand. I was just curious because I've been writing a series of blog posts on FFmpeg lately. Perhaps I'll cover the performance gains in my blog, with statistics from .NET Profiler. Perhaps.

As for the PR, you can take it, cherry-pick, or leave it. It's your call. Have a nice day. 😊And again, thanks for everything.

**Pull request closed without merging**
