### PR TITLE
Add aribb24 for ARIB caption support

### PR DESCRIPTION
**Pull request by shirt-dev**
This PR adds support for libaribb24, a library used for decoding closed captioning from ISDB streams, commonly used on Japanese TV.

### CODE REVIEW

**Comment by BtbN** [comment]
Is that patch really needed? zlib.h should be easily available at that stage.

**Comment by shirt-dev** [comment]
Builds seemed to fail unless I had the patch added.

**Comment by shirt-dev** [comment]
Here is the result of the build without the patch:
```
------
 > [layer-25-libpng 1/1] RUN --mount=src=scripts.d/25-libpng.sh,dst=/stage.sh run_stage /stage.sh:
#20 7.648 mv pnglibconf.tf5 pnglibconf.c
#20 7.650 rm -f pnglibconf.out pnglibconf.tf[12]
#20 7.652 test -d scripts || mkdir scripts || test -d scripts
#20 7.654 x86_64-w64-mingw32-gcc -E -DHAVE_CONFIG_H -I. \
#20 7.654      -DPNGLIB_LIBNAME='PNG16_0' -DPNGLIB_VERSION='1.6.35' -DSYMBOL_PREFIX='' -DPNG_NO_USE_READ_MACROS -DPNG_BUILDING_SYMBOL_TABLE  pnglibconf.c > pnglibconf.tf1
#20 7.660 pnglibconf.c:33:11: fatal error: zlib.h: No such file or directory
#20 7.660    33 | # include <zlib.h>
#20 7.660       |           ^~~~~~~~
#20 7.661 compilation terminated.
#20 7.662 make: *** [Makefile:2316: pnglibconf.out] Error 1
------
```
https://github.com/shirt-dev/FFmpeg-Builds/runs/6166520330

**Comment by BtbN** [comment]
Does aribb even need libpng? It seems optional, though I have no experience with the format, so not sure what it's used for.

**Comment by shirt-dev** [comment]
> Does aribb even need libpng? It seems optional, though I have no experience with the format, so not sure what it's used for.

It requires libpng for DRCS character decoding. https://github.com/nkoriyama/aribb24/blob/master/src/drcs.c

**Comment by BtbN** [comment]
Figured out how to properly build libpng (please don't randomly patch out includes that are somewhat important :D )
And pulled a couple patches for aribb. Also artificially bumped its version, so ffmpeg doesn't see it as gpl-only anymore, as the license has long been changed to lgpl.

**Comment by shirt-dev** [comment]
Thank you!

**Pull request closed without merging**
