### PR TITLE
Add Functional Readme Badges

### PR DESCRIPTION
**Pull request by sudo-nautilus**
That's it,
A reping

### CODE REVIEW

**Comment by sudo-nautilus** [comment]
Um,
@BtbN what I want to do with this ?

**Comment by BtbN** [comment]
I haven't decided yet. Still not a huge fan of badges. They seem like added weight to a otherwise text only readme, without really any benefit.

**Comment by sudo-nautilus** [comment]
I think that's correct,
Isn't it the time to close this pr ?

**Comment by BtbN** [comment]
What would be cool and I'd instantly add was some way to generate links that always point to the latest release of a specific type, in a way that wget/curl can just pick up.
But I don't see any way to do that with just Github tools.

**Comment by sudo-nautilus** [comment]
There's a way, I guess,
Have you ever tried of GitHub pages ?

**Comment by BtbN** [comment]
I'm thinking of an actual http link directly to the file. Not some HTML page with a link. That's already in the wiki.
I guess pushing the archives directly to the gh-pages is an option, but it seems very ugly and might need git-lfs.

**Comment by sudo-nautilus** [comment]
I too am thinking about that. We can actually do that by making the repo capable to become a webpage too. I'll make a pull request soon.

**Comment by BtbN** [comment]
I'd rather not have large binary files in the git repo, that's not an appropriate solution and will result in a humongous unmanageable history.

**Comment by sudo-nautilus** [comment]
> I'd rather not have large binary files in the git repo, that's not an appropriate solution and will result in a humongous unmanageable history.

I was thinking about that while I was sleeping,
So I decided to try to make a site for that purpose.

**Comment by sudo-nautilus** [comment]
That thing doesn't work :(

**Comment by sudo-nautilus** [comment]
I think we can actually do that

**Comment by sudo-nautilus** [comment]
By writing another remote repository after the builds are succeeded.

**Pull request closed without merging**
