### PR TITLE
Update SVT-AV1 to v1.3.0

### PR DESCRIPTION
**Pull request by mrintrepide**
PR for issue #204 

Change SVT-AV1 commit tag to v1.3.0

PR for issue #203 

Enable AVX512 support for SVT-AV1

### CODE REVIEW

**Comment by BtbN** [comment]
I'm very much unsure about enabling AVX512.
Why is it disabled by default?
What are the implications for non-AVX512 systems?

**Comment by mrintrepide** [comment]
Sorry for AVX512 commit.
I already try to build AVX512 enabled build on non-AVX512 VM and test video encode.

**Comment by mrintrepide** [comment]
I build SvtAv1EncApp directly with and without avx512 support on virtual machine without avx512 (qemu-kvm Epyc processor) and it works.
I convert the same video with this VM without avx512 and in my host machine with avx512 with both SvtAv1EncApp build and it produce the same output. (Same checksum)

Svt-Av1 use "--asm" flag to change cpu instruction (Limit assembly instruction set [c, mmx, sse, sse2, sse3, ssse3, sse4_1, sse4_2, avx, avx2, avx512, max])

Svt[info]: [asm level on system : up to avx512]
Svt[info]: [asm level selected : up to avx2]

**Comment by BtbN** [comment]
Why is it default disabled then? My concern is that the code is untested and can crash or produce other problems in certain scenarios.

**Comment by mrintrepide** [comment]
I think it's for [CI](https://gitlab.com/AOMediaCodec/SVT-AV1/-/pipelines/674342861), some old compiler not support AVX512

**Pull request merged**
